name: Deployment pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: E2E Test
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run dev
          wait-on: http://localhost:3000
